name: Frontend CI/CD
on:
#  push:
#    branches:
  #    - main
  workflow_dispatch:
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: frontend
  CONTAINER_NAME: frontend
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        working-directory: frontend
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.run_number }} .
          docker tag $ECR_REPOSITORY:${{ github.run_number }} \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.run_number }}

      - name: Push Docker Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.run_number }}

      - name: Stop Existing Container
        run: |
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true

      - name: Pull Latest Image
        run: |
          docker pull \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.run_number }}

      - name: Run Frontend Container
        run: |
          docker run -d \
            --name $CONTAINER_NAME \
            --restart always \
            -p 8501:8501 \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.run_number }}

      - name: Verify Container
        run: docker ps

      - name: Show Running Containers
        if: always()
        run: docker ps -a

      - name: Show Docker Images
        if: always()
        run: docker images
